src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Repository\TournamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TournamentRepository::class)]
class Tournament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $nbr_team_max = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $rule = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\OneToMany(mappedBy: 'tournament', targetEntity: Teams::class)]
    private Collection $teams;

    #[ORM\OneToMany(mappedBy: 'tournament', targetEntity: Matches::class)]
    private Collection $matches;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->matches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNbrTeamMax(): ?int
    {
        return $this->nbr_team_max;
    }

    public function setNbrTeamMax(int $nbr_team_max): static
    {
        $this->nbr_team_max = $nbr_team_max;

        return $this;
    }

    public function getRule(): ?string
    {
        return $this->rule;
    }

    public function setRule(string $rule): static
    {
        $this->rule = $rule;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection<int, Teams>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Teams $team): static
    {
        if (!$this->teams->contains($team)) {
            $this->teams->add($team);
            $team->setTournament($this);
        }

        return $this;
    }

    public function removeTeam(Teams $team): static
    {
        if ($this->teams->removeElement($team)) {
            // set the owning side to null (unless already changed)
            if ($team->getTournament() === $this) {
                $team->setTournament(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Matches>
     */
    public function getMatches(): Collection
    {
        return $this->matches;
    }

    public function addMatch(Matches $match): static
    {
        if (!$this->matches->contains($match)) {
            $this->matches->add($match);
            $match->setTournament($this);
        }

        return $this;
    }

    public function removeMatch(Matches $match): static
    {
        if ($this->matches->removeElement($match)) {
            // set the owning side to null (unless already changed)
            if ($match->getTournament() === $this) {
                $match->setTournament(null);
            }
        }

        return $this;
    }
}

src/Form/TournamentType.php
<?php

namespace App\Form;

use App\Entity\Tournament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TournamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('nbr_team_max')
            ->add('rule')
            ->add('date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tournament::class,
        ]);
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Tournament;
use App\Form\TournamentType;
use App\Repository\TournamentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tournament')]
class TournamentController extends AbstractController
{
    #[Route('/show', name: 'app_tournament_index', methods: ['GET'])]
    public function index(TournamentRepository $tournamentRepository): Response
    {
        return $this->render('tournament/index.html.twig', [
            'tournaments' => $tournamentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tournament_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($tournament);
            $entityManager->flush();

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_show', methods: ['GET'])]
    public function show(Tournament $tournament): Response
    {
        return $this->render('tournament/show.html.twig', [
            'tournament' => $tournament,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tournament_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_delete', methods: ['POST'])]
    public function delete(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournament->getId(), $request->request->get('_token'))) {
            $entityManager->remove($tournament);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tournament/_delete_form.html.twig
<form method="post" action="{{ path('app_tournament_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tournament/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournament{% endblock %}

{% block body %}
    <h1>Edit Tournament</h1>

    {{ include('tournament/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_tournament_index') }}">back to list</a>

    {{ include('tournament/_delete_form.html.twig') }}
{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament index{% endblock %}

{% block body %}
    <h1>Tournament index</h1>
<style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
        }
        th {
            background-color: #555;
            color: #fff;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        p {
            text-align: center;
            color: #888;
        }
        .custom-link {
            color: #007bff;
            text-decoration: none;
            font-weight: bold;
            border-bottom: 2px solid transparent;
            transition: border-bottom 0.3s ease;
        }
        .custom-link:hover {
            border-bottom: 2px solid #007bff;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            
        }
        .custom-button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            text-align: center;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;    
            transition: background-color 0.3s ease;
        }
        .custom-button:hover {
            background-color: #45a049;
        }
    </style>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Nbr_team_max</th>
                <th>Rule</th>
                <th>Date</th>
                <th>information</th>
                <th>Modification</th>
            </tr>
        </thead>
        <tbody>
        {% for tournament in tournaments %}
            <tr>
                <td>{{ tournament.id }}</td>
                <td>{{ tournament.name }}</td>
                <td>{{ tournament.nbrTeamMax }}</td>
                <td>{{ tournament.rule }}</td>
                <td>{{ tournament.date ? tournament.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_tournament_show', {'id': tournament.id}) }}">Plus d'information</a>
                    </td>
                    <td>
                    <a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table">
<div class="container">
   <td> <a href="{{ path('app_tournament_new') }}" class="custom-link">Create new</a></td>
    </div>
<td> <a href="{{ path('app_acceuil_index') }}" class="custom-link">Retour a la page d'acceuil</a> </td>
    
    </table>
{% endblock %}

templates/tournament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournament{% endblock %}

{% block body %}
    <h1>Create new Tournament</h1>

    {{ include('tournament/_form.html.twig') }}

    <a href="{{ path('app_tournament_index') }}">back to list</a>
{% endblock %}

templates/tournament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}
    <h1>Tournament</h1>
<style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
        }
        th {
            background-color: #555;
            color: #fff;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        p {
            text-align: center;
            color: #888;
        }
        .custom-link {
            color: #007bff;
            text-decoration: none;
            font-weight: bold;
            border-bottom: 2px solid transparent;
            transition: border-bottom 0.3s ease;
        }
        .custom-link:hover {
            border-bottom: 2px solid #007bff;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
           
        }
        .custom-button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            text-align: center;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;    
            transition: background-color 0.3s ease;
        }
        .custom-button:hover {
            background-color: #45a049;
        }
    </style>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tournament.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ tournament.name }}</td>
            </tr>
            <tr>
                <th>Nbr_team_max</th>
                <td>{{ tournament.nbrTeamMax }}</td>
            </tr>
            <tr>
                <th>Rule</th>
                <td>{{ tournament.rule }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ tournament.date ? tournament.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <table class="table">
    <div class="container">
   <td> <a href="{{ path('app_tournament_index') }}" class="custom-link">back to list</a> </td>

    <td><a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}" class="custom-link">edit</a></td>

   <td>  {{ include('tournament/_delete_form.html.twig') }}</td>
    </table>
{% endblock %}